name: Execute notebook

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'
    - run: python3 -m pip install AgamPrimer nbformat ipykernel papermill nbconvert
    - run: python -m ipykernel install --user --name AgamPrimer
    - run: papermill notebooks/AgamPrimer-long.ipynb qPCR_run.ipynb -k AgamPrimer -f tests/cDNA_Params.json
    - run: papermill notebooks/AgamPrimer-long.ipynb qPCR2_run.ipynb -k AgamPrimer -f tests/cDNA_Params_2.json
    - run: papermill notebooks/AgamPrimer-long.ipynb gDNA_run.ipynb -k AgamPrimer -f tests/gDNA_probe_Params.json
    - run: papermill notebooks/AgamPrimer-long.ipynb probe_run.ipynb -k AgamPrimer -f tests/probe_Params.json
    - run: papermill notebooks/AgamPrimer-short.ipynb short_run.ipynb -k AgamPrimer
