name: Execute notebooks

on:
  push:
      branches:
          - main
  pull_request:
      branches:
          - main

jobs:

  run:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
          python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:

    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install poetry
      run: pipx install poetry==1.4.2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'

    - name: Install dependencies
      run: |
        poetry install
        poetry run python -m ipykernel install --user --name AgamPrimer

    - name: Run notebooks
      run: |
        poetry run papermill notebooks/AgamPrimer-long.ipynb qPCR_run.ipynb -k AgamPrimer -f tests/cDNA_Params.json
        poetry run papermill notebooks/AgamPrimer-long.ipynb qPCR2_run.ipynb -k AgamPrimer -f tests/cDNA_Params_2.json
        poetry run papermill notebooks/AgamPrimer-long.ipynb gDNA_run.ipynb -k AgamPrimer -f tests/gDNA_probe_Params.json
        poetry run papermill notebooks/AgamPrimer-long.ipynb probe_run.ipynb -k AgamPrimer -f tests/probe_Params.json
        poetry run papermill notebooks/AgamPrimer-short.ipynb short_run.ipynb -k AgamPrimer
