name: notebooks-gambiae

on:
  push:
      branches:
          - main
  pull_request:
      branches:
          - main

jobs:

  run:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
          python-version: ['3.8', '3.11']

    steps:

    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install poetry
      run: pipx install poetry==1.4.2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'

    - name: Install dependencies
      run: |
        poetry install
        poetry run python -m ipykernel install --user --name AnoPrimer

    - id: 'auth'
      name: 'Set up Google Cloud authentication'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: 'Set up Google Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'

    - name: 'Check gcloud CLI'
      run: 'gcloud info'

    - name: Run notebooks
      run: |
        poetry run papermill notebooks/AnoPrimer-long.ipynb qPCR_run.ipynb -k AnoPrimer -f tests/cDNA_Params.json
        poetry run papermill notebooks/AnoPrimer-long.ipynb qPCR2_run.ipynb -k AnoPrimer -f tests/cDNA_Params_2.json
        poetry run papermill notebooks/AnoPrimer-long.ipynb gDNA_run.ipynb -k AnoPrimer -f tests/gDNA_probe_Params.json
        poetry run papermill notebooks/AnoPrimer-long.ipynb probe_run.ipynb -k AnoPrimer -f tests/probe_Params.json
        poetry run papermill notebooks/AnoPrimer-short.ipynb short_run.ipynb -k AnoPrimer
